# Generated by Django 5.1 on 2024-08-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='allergen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown'), ('Unsexed', 'Unsexed')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Tortoise', 'Tortoise'), ('Lizard', 'Lizard'), ('Other', 'Other')], max_length=10),
        ),
    ]
