# Generated by Django 5.1 on 2024-08-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_rename_adopted_pet_under_adoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdonationrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets-images/'),
        ),
        migrations.AlterField(
            model_name='petdonationrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petdonationrequest',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.petshelter'),
        ),
    ]
