# Generated by Django 5.1 on 2024-08-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_petdonationrequest_image_alter_petdonationrequest_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetDonationRequest',
        ),
    ]
