# Generated by Django 5.1 on 2024-08-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Toy', 'Toy'), ('Accessory', 'Accessory'), ('Grooming', 'Grooming'), ('Health', 'Health'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet-images/')),
            ],
            options={
                'verbose_name': 'Pet Item',
                'verbose_name_plural': 'Pet Items',
            },
        ),
    ]
